### ISSUE TITLE
建议去除元宵节、情人节等非法定假日日历事件

### ISSUE THREAD

**Issue by alswl** [xbf321/iCal#1]
建议去除元宵节、情人节等非法定假日日历事件。
严格遵循：http://www.gov.cn/zhengce/content/2019-11/21/content_5454164.htm 给出的放假、上班信息。

中国假日可以使用 Apple 官方发布的 iCal：https://p39-calendars.icloud.com/holidays/cn_zh.ics

**Comment by xbf321** [comment]
元宵节，情人节虽然不是法定假日，也不放假，但表出来也无妨，给大家一个提醒。
另外，Apple 官方假日，不包含连休以及上班信息。这也是自己处理的最主要原因。

**Comment by alswl** [comment]
这导致了信息分类的不纯粹。

Apple 官方假日，就是纯粹为了中国假日提醒，不包含放假信息。
