### ISSUE TITLE
2024年  部分节假日安排

### ISSUE THREAD

**Issue by uyoungco** [xbf321/iCal#3]
一、元旦：1月1日放假，与周末连休。

二、春节：2月10日至17日放假调休，共8天。2月4日（星期日）、2月18日（星期日）上班。

三、清明节：4月4日至6日放假调休，共3天。4月7日（星期日）上班。

四、劳动节：5月1日至5日放假调休，共5天。4月28日（星期日）、5月11日（星期六）上班。

五、端午节：6月10日放假，与周末连休。

六、中秋节：9月15日至17日放假调休，共3天。9月14日（星期六）上班。

七、国庆节：10月1日至7日放假调休，共7天。9月29日（星期日）、10月12日（星期六）上班。

**Comment by xbf321** [comment]
已经更新，感谢反馈。
